name: primeira-pipeline

on:
  ## Evento que gatilha a pipeline
  push: ## Um commit na branch
    branches: ["main"]
    
  workflow_dispatch: ## Permite executar a pipeline manualmente, pelo painel do Github.

jobs:
  primeiro-job:
    name: "meu-primeiro-job"
    runs-on: ubuntu-latest  ## Runner, ambiente onde as tarefas declaradas serão executadas.
    steps: ## Onde de fato são declaradas as actions
      - name: "Minha primeira action"
        run: echo "Hello World!"
      - name: "Segunda action"
        run: | ## Pipe é usado para executar diversas instruções na mesma action.
          echo "Você criou o seu primeiro Workflow!"
          echo "Parabéns!"
      - name: "Script Python"
        run: |
          variavel = "Hello World!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalando ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificar versão do NodeJS atual"
        run: node --version
      - name: "Definindo versão 22.12.0 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
      - name: "Verificar versão do NodeJS atual"
        run: node --version
